module.exports = {
	products: [
		{
		_id:'1', 
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: '/images/Sika3SC.jpg',
		price: 60,
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'2', 
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: '/images/Sika1.jpg',
		price: 60,
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'3',
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: '/images/Sika3.jpg',
		price: 60,
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'4', 
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: '/images/SikaGuard63Esmalte.jpg',
		price: 60,
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'5', 
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: '/images/SikaLatex.jpg',
		price: 60,
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'6',
		 name: '1',
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: '/images/SikaWT100.jpg',
		price: 60,
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
			    ],
};