module.exports = {
	products: [
		{
		_id:'1', 
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: '/images/Sika3SC.jpg',
		price: 60,
		size: 6"kg",
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'2', 
		name: 'Sika 1',
		category: 'acelerante',
		image: '/images/Sika1.jpg',
		price: 60,
		size: 10"l",
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'3',
		name: 'Sika 3',
		category: 'acelerante',
		image: '/images/Sika3.jpg',
		price: 60,
		size: 6 'kg',
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'4', 
		name: 'Sika Guard 63 Esmalte',
		category: 'acelerante',
		image: '/images/SikaGuard63Esmalte.jpg',
		price: 60,
		size: 10'l',
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'5', 
		name: 'Sika Latex',
		category: 'acelerante',
		image: '/images/SikaLatex.jpg',
		price: 60,
		size: 5 'l',
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
		{
		_id:'6',
		 name: '1',
		name: 'Sika WT-100',
		category: 'acelerante',
		image: '/images/SikaWT100.jpg',
		price: 60,
		size: 20'kg',
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 1,
		},
			    ],
};