export default {
	 mode: 'development',
	products: [
			{
		_id:'1', 
		name: 'Sika 1',
		category: 'acelerante',
		image: '/images/Sika1.jpg',
		price: 1100,
		size: 10 + "L",
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 6,
		description: 'Aditivo líquido que reacciona con los componentes de la mezcla de cemento y arena para bloquear los capilares y poros de morteros y hormigones. Impide el paso del agua y permite la respiración del sustrato.',
		},
		{
		_id:'2',
		name: 'Sika 3',
		category: 'acelerante',
		image: '/images/Sika3.jpg',
		price: 1200,
		size: 6 + 'kg',
		brand: 'Sika',
		rating: 3,
		numReviews: 10,
		countinStock: 5,
		description: 'Aditivo acelerador del fraguado y endurecimiento, a base de cloruros, actúa aumentando la velocidad de hidratación y las reacciones químicas de los constituyentes del cemento.',
		},
		{
		_id:'3', 
		name: 'Sika 3 sin cloruro',
		category: 'acelerante',
		image: './images/Sika3SC.jpg',
		price: 3200,
		size: 6 + "kg",
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 3,
		description: ' Aditivo desarrollado especialmente para acelerar el fragüe de morteros y hormigones armados. No contiene cloruros. No corroe las armaduras ni los insertos metálicos.',
		},
		{
		_id:'4', 
		name: 'Sika Guard 63 Esmalte',
		category: 'acelerante',
		image: '/images/SikaGuard63Esmalte.jpg',
		price: 10300,
		size: 10 + 'L',
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock:10,
		description: 'Producto de dos componentes a base de resinas epoxídicas, fácil de mezclar, aplicable a pincel, rodillo o pistolas a aire. Constituye una excelente protección química, mecánica y anticorrosiva.',
		},
		{
		_id:'5', 
		name: 'Sika Latex',
		category: 'acelerante',
		image: '/images/SikaLatex.jpg',
		price: 5000,
		size: 5 + 'L',
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 8,
		description: 'Emulsión a base de resinas sintéticas, que agregada al agua de empastado de lechadas de cemento, les aporta alta capacidad de adherencia entre diferentes etapas de construcción. Además, incorporado al agua de empastado de morteros, les mejorará la calidad logrando cohesión entre las partículas, aumentando su adherencia, mejorando su flexibilidad y disminuyendo la capacidad de absorber agua.',
		},
		{
		_id:'6',
		 name: '1',
		name: 'Sika WT-100',
		category: 'acelerante',
		image: '/images/SikaWT100.jpg',
		price: 14500,
		size: 20 + 'kg',
		brand: 'Sika',
		rating: 4.5,
		numReviews: 10,
		countinStock: 9,
		description: 'Aditivo líquido que resiste la entrada de agua usado para reducir la permeabilidad del hormigón.',
		},
			    ],
					};